FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Music Curation Manager

An api for managing curations (playlists).

# Group Curations
Resources related to curations.

## Curations Collection [/curations]

### List All Curations [GET]
+ Response 200 (application/json)
    + Attributes (array[Playlist])

## Curation [/curation/{curation_id}]
+ Parameters 
    + curation_id (required, number , `1`)

### List single Curation [GET]
+ Response 200 (application/json)
    + Attributes (Curation)

# Data Structures

##Curation (object)
+ id: 1 (number)
+ created: 1521237557525 (number) - Unix time stamp when created
+ duration: 1:22:54 (string)  - Total length of playlist
+ environment: production (string) - Current runtime environment
+ listeners: 3456 (number) - The number of subscribers for this curation
+ published: 1521237557525 (number) - Unix time stamp when published
+ scheduled: 1521245675667 (number) - Unix time stamp when scheduled
+ songTitles: Dogs of Winter, Pants Wearer, Cancel the Prom, Apes of Wrath (array[string]) - List of song titles in curation
+ status: draft (string) - Publication status
+ tags (array[Tag]) - A collection of associated tags
+ title: Banks of money and sand (string) - Title of the curation
+ updated: 1521245675667 (number) - Unix time stamp when last updated

## Tag (object)
+ id: 1 (number) - Tag id
+ title: Dumb (string) - Tag title

## Song (object)
+ id: 3 (number)
+ artist: Cadaver Sandwich (string)
+ duration: 3:43 (string)
+ recordLabel: DougPound Inc array[string],
+ tags: Good, Bad (array[Tag])

## Track (object)
+ id: 0 (number)
+ externalId: 54219314 (string)
+ artistName: Drake (string)
+ trackName: One Dance (string)
+ durationInSeconds: 174 (number)
+ streamUrl: http://www.dev.com/api/Track/Stream?trackId=54219314 (string)
+ imageUrl: http://artwork-cdn.7static.com/static/img/sleeveart/00/053/498/0005349842_800.jpg (string)
        
## Playlist (object)
+ id: 1 (number)
+ type: 1 (number) - Playlist types are: 1: Collection, 2: Curation, 3: Stream, 4: Album
+ name: Morning Workout (string)
+ imageUrl: https://cdn.muscleandstrength.com/sites/all/themes/mnsnew/images/taxonomy/workouts/bicep.jpg (string)
+ tracks (array[Track])

## Artist (object)
+ id: 142111 (string)
+ type: 1 (number)
+ name: Adele (string)
+ imagUrl: http://artwork-cdn.7static.com/static/img/artistimages/00/001/421/0000142111_300.jpg (string)
+ infoUrl (string)
+ genres (string)
+ desc (string)
+ tracks (array[Track])
+ albums (array[Playlist])
+ playlists (array[Playlist])
+ similarArtists (array[Artist])




